name = "anime-api-cache"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "CACHE"
id = "90ca1f8463914189b4964a95bdfe92f0"

[vars]
ANILIST_URL = "https://graphql.anilist.co"
JIKAN_URL = "https://api.jikan.moe/v4"
CACHE_TTL = "1800"
ALLOWED_ORIGINS = "https://watchanimez.me,https://www.watchanimez.me,http://localhost:5173,http://localhost:4173"
